version: '3.8'

services:
  image-processor:
    build: .
    ports:
      - "8003:8003"
    environment:
      - PORT=8003
      - HOST=0.0.0.0
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
